### ISSUE TITLE
Error: Internal Error: Identifier "acl" is not defined.

### ISSUE THREAD

**Issue by asangansi** [EpocDotFr/kanboard-wunderlist#2]
I get this error after uploading to plugins/Wunderlist folder as in instructions

**Comment by asangansi** [comment]
I'm using latest versions of kanboard and kanboard-wunderlist

**Comment by EpocDotFr** [comment]
Thanks for reporting. I'll take a look :)

**Comment by EpocDotFr** [comment]
Can you test with the latest master version? https://github.com/EpocDotFr/kanboard-wunderlist/archive/master.zip

**Comment by EpocDotFr** [comment]
There's another issue when accessing the import page. I'll fix it tomorrow

**Comment by EpocDotFr** [comment]
Can you test with the latest master version? https://github.com/EpocDotFr/kanboard-wunderlist/archive/master.zip

**Comment by marius-zenitech** [comment]
I have same problem with latest version but don't use/have wunderlist plugin

**Comment by EpocDotFr** [comment]
@Sorasma You have another plugin which is out of date.

**Comment by marius-zenitech** [comment]
Yep, I was using 2-3 builds older versions and it was the "AutomaticAction" plugin, seems that new version doesn't have that plugin anymore. All working fine now.
Thanks :)

**Comment by EpocDotFr** [comment]
All bugs fixed now. Please upgrade to [1.0.1](https://github.com/EpocDotFr/kanboard-wunderlist/releases/tag/v1.0.1).

**Comment by asangansi** [comment]
I just tested, and its all working well now. Thanks!
