### ISSUE TITLE
Call to undefined method Kanboard\\Core\\Template::layout()

### ISSUE THREAD

**Issue by chalvorsonjr** [EpocDotFr/kanboard-wunderlist#4]
I'm using Kanboard v1.0.27 and kanboard-wunderlist v1.0.1.  When I go to the **Preferences > Import from Wunderlist** menu, I get a HTTP 500 server error.

The Apache log entry is

> [Fri Apr 01 10:10:45.791866 2016] [:error] [pid 12340:tid 1016] [client ::1:58168] PHP Fatal error:  Call to undefined method Kanboard\Core\Template::layout() in C:\apache2\htdocs\kanboard\plugins\Wunderlist\Controller\Wunderlist.php on line 34

**Comment by EpocDotFr** [comment]
Thank you for your feedback. I will test kanboard-wunderlist tomorrow and release a new version to be compatible with the latest of kanboard

**Comment by EpocDotFr** [comment]
Please upgrade to 1.0.3 : https://github.com/EpocDotFr/kanboard-wunderlist/releases/tag/v1.0.3

**Comment by chalvorsonjr** [comment]
Works good... imported ~120 projects/tasks without issue.  Thank you.

**Comment by EpocDotFr** [comment]
Glad to read that :+1:
