### ISSUE TITLE
get HTTP error 500 ?

### ISSUE THREAD

**Issue by LeCanardNoir** [EpocDotFr/kanboard-wunderlist#5]
When i click on "impost Wunderlist...." , i get this page error HTTP 500

**Comment by LeCanardNoir** [comment]
Fatal error: Call to undefined method Kanboard\Core\Template::layout() in /Applications/MAMP/htdocs/kanboard/plugins/Wunderlist/Controller/Wunderlist.php on line 34

**Comment by EpocDotFr** [comment]
This bug has been fixed in [1.0.3](https://github.com/EpocDotFr/kanboard-wunderlist/releases/tag/v1.0.3). Please update your plugin and keep me informed if you still encounter this issue.
