### ISSUE TITLE
Error on install with Kanbaord 1..47

### ISSUE THREAD

**Issue by neuralgraffiti** [EpocDotFr/kanboard-wunderlist#8]
Hi, installing with latest stable Kanboard (1.0.47.) results in the error:
`Internal Error: Identifier "config" is not defined.`
on each page.  I'm assuming there's been drift since Kanboard 1.0.34?

**Comment by EpocDotFr** [comment]
Hello,

Yes, the plugin wasn't updated for a while. I'll update it to be compatible with the latest Kanboard tomorrow.

**Comment by EpocDotFr** [comment]
FYI Kanboard  1.0.48 was released yesterday evening.

**Comment by EpocDotFr** [comment]
I [released](https://github.com/EpocDotFr/kanboard-wunderlist/releases/tag/v1.0.4) a minor release but I didn't make any significant changes.

When I tested my plugin with the latest Kanboard and with a fresh Wunderlist export file, everything worked as expected without any error. I'm using PHP 5.6.12.

Do you have details about this error? File, line number, etc?

**Comment by neuralgraffiti** [comment]
I installed the latest Kanboard and the updated plugin and am not getting the error anymore. Thanks!
