### ISSUE TITLE
Incompatible to Kanboard Version 1.1.1

### ISSUE THREAD

**Issue by CMiksche** [EpocDotFr/kanboard-wunderlist#9]
Due to the function getCompatibleVersion() in Plugin.php with the return parameter "1.0.48" is this Plugin not compatible with Kanboard 1.1.1.

I have changed the version to 1.1.1 in my local copy. The page "Import from Wunderlist" is shown in my copy.
With sqlite i get an Error 504 from my hosting provider (i tested it on webspace, not on a own server), with mysql everything works fine.

**Comment by CMiksche** [comment]
I fixed the issue in Pull request #10 by allowing higher versions than 1.0.48 in the Plugin.php.

**Comment by EpocDotFr** [comment]
Hey, thank you! Merging now. Sorry I'm a bit overbooked since it's the end of the year.
